language: julia
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success: 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
